### ISSUE TITLE
event overlaps, with events as a computed property

### ISSUE THREAD

**Issue by eladyaniv01** [antoniandre/vue-cal-v4#116]
Hello,  
First of all, i admire the work done here,  amazing project,
the problem i am facing right now is, if i want to apply the `no-event-overlaps` method,  it only works with non-computed events  ( i assume maybe im doing something wrong ?) 
in my case the events are a computed property, 
i am getting them from the store,  and serialize them into the Calendar specific data model 
everything works nicely,  the only thing that doesnt is `no-event-overlaps`
is it a bug ? 
or am i using it wrong ? 

Thanks, 
Elad

**Comment by antoniandre** [comment]
Hi @eladyaniv01, 
Thank you for your feedback I appreciate it.
Regarding the issue, I just want to make sure that you understood that `no-event-overlaps` still allow multiple events on the same time, but only the display will change as per this example https://antoniandre.github.io/vue-cal/#ex--overlapping-events, when you click the button.

if that is what you had in mind, perfect, then I will need some code sharing to help you 😃

**Comment by antoniandre** [comment]
Maybe you can fork and modify this if it helps: https://codepen.io/antoniandre/pen/eoEgqo

**Comment by eladyaniv01** [comment]
yes,  it did help,  i was able to reproduce the problem,  i have copied the exact array of events that is computed from my store,   maybe you can find what i have done wrong
It's worth to note that i render events in a custom manner, (you will see unique attr's there, such as client, nutritionist, and so on ,  its for maping scheduled meetings)


https://codepen.io/eladyaniv01/pen/YbNaRm

**Comment by antoniandre** [comment]
Hi @eladyaniv01, 
Great, thank you for the reproduction link. I tried it and see the issue here.
The fact that your events come from a Vuex Store and through a computed value is totally fine.
What happens here is that when the events are in background (`background: true`), they will overlap unconditionally this is purposely done to allow such behavior in this example: https://antoniandre.github.io/vue-cal/#ex--background-events

So removing the background property will fix the problem.

Hope it helps.

**Comment by antoniandre** [comment]
Hi @eladyaniv01, 
Great, thank you for the reproduction link. 
I tried it and see the issue here.
The fact that your events come from a Vuex Store and through a computed value is totally fine.
What happens here is that when the events are in background (`background: true`), they will overlap unconditionally this is purposely done to allow such behavior in this example: https://antoniandre.github.io/vue-cal/#ex--background-events

So removing the background property will fix the problem.

Hope it helps.

**Comment by eladyaniv01** [comment]
Thanks you so much for your quick response and clear explanation , much appreciated
It works, i am closing the issue, 

Please let me know if i can contribute to your project!

**Comment by eladyaniv01** [comment]
Thank you !
it works like a charm

**Comment by antoniandre** [comment]
Awesome @eladyaniv01.
If you are willing to contribute on Vue Cal you are always welcome!

I will have a look if I can find a not-too-complex task for you as a good start and will let you know. Probably right after the V2 release as I am refactoring everything that would cause lots of annoying conflicts.

**Comment by antoniandre** [comment]
Hi @eladyaniv01, 
The v2 is out for a while now and I just remembered you asking to help.
If you still feel like contributing that's awesome! Otherwise, no problem at all! 👌 

- If you wanted to contribute code:

  You can pick any of the open issues as long as you let me know what you are working on so we won't do the same thing!
  You can also email me if you want more direction and/or assistance on the task and where to start, I'll be happy to get in touch.
  You'll find my email in here: https://github.com/antoniandre/vue-cal/blob/master/package.json.


- If you wanted to support with a donation there is a donation page [here](https://www.paypal.me/antoniandre1).

Thanks for your help!
Cheers, Antoni
