### ISSUE TITLE
attach vue-cal 

### ISSUE THREAD

**Issue by DimaBDV** [antoniandre/vue-cal-v4#12]
Hello. I can't attach Vue-Cal to my Laravel project.
What am I doing wrong?

my template "cal.blade.php"
`<m-cal></m-cal>`

my "app.js"
`Vue.component('m-cal', require('./components/vCal.vue'));`

my "vCal.vue"
`<template> </template>`
`<script>`
   ` import Vuecal from 'vue-cal'`
   ` import 'vue-cal/dist/vuecal.css'`

    export default {
    mounted() {
        console.log('Vuecal mounted')
    },
    components: { Vuecal },
    
    data: () => ({

    }),
`}
</script>`

So does not work!

But i add in `<template> <VC></VC> </template>` and `<script> ... components: { VC : Vuecal }, ... </script>`
It starts to work, but not by the size of the container (as indicated in the documentation), but optional (I have 450 px in height -> "height not !important " )

trouble picture
https://pp.userapi.com/c844216/v844216049/15d8ae/ucnFpDgwk4k.jpg

**Comment by antoniandre** [comment]
Hi @DimaBDV,

Thanks for your interest in vue-cal.
I can see that your second trial is successful because you use the tag `<vc>`that you registered: `components: { VC : Vuecal }` and everything is straightforward here.

In the first attempt, you are misusing the `Vue.component` function, which complains in the error logs that there is no template.

To fix it with the same way you want (double component declaration), you need to write it like this:

```vue
import Vue from 'vue'
const mcal = require('./components/vCal.vue')

Vue.component('m-cal', mcal.default);

```

As the whole `vCal.vue` component resides in an `export default`.

You can now use the tag `<m-cal></m-cal>` in your template.


_____

Regarding the height of vue-cal, 
as written in documentation it will occupy the full height of its parent if the parent has an explicitly set height. like `style="height: 500px"`.

If the parent does not have a set height, you can still put a height on the vue-cal component the same way: `style="height: 500px"`.

Hope it solves your problems!

**Comment by DimaBDV** [comment]
@antoniandre 
Thank you very much!!! It works now!
This issue may be closed.
_______________________

The question is off topic. But if possible.
How can I set the event indicator on month view. I see that it is planned, but maybe there is some way?
I can do this with 
Check title (year/month)
`$('.vuecal').find('.vuecal__title').find('.clickable').text() == '(string)Mounth (int)Year'`
and use
`.find([
.vuecal__cell,
.today,
.out-of-scope
])`

**Comment by antoniandre** [comment]
Hi @DimaBDV, glad it fixes your problem.
Regarding the event indicator you could hack something with jQuery as you have it but I doubt it would be a good and stable solution.
If you are happy to wait, I will release this feature in a couple versions, probably beginning of January.

**Comment by antoniandre** [comment]
Hi @DimaBDV, 
I have released the events indicators on month view! 
You can have a look at the **# Month view with events indicators** example. 
Also check the [release notes](https://antoniandre.github.io/vue-cal/#release-notes) for the last updates.

I am closing your initial issue now, you can open a new one if it's not related to your initial issue. 👌
