### ISSUE TITLE
Events are not shown in week view in case of multiple days event with 00:00:00 endtime

### ISSUE THREAD

**Issue by louhuaidong** [antoniandre/vue-cal-v4#139]
Condition: 
start:  2019-07-12 00:00:00
end:  2019-07-14 00:00:00

Possible Root cause:
In cell.vue, multiple days event case is not considered in events():get():line 189

**Comment by antoniandre** [comment]
Thanks for reporting @louhuaidong, this will be fixed in the v2 coming very soon.
Meantime you can set an end time at 23.59

**Comment by antoniandre** [comment]
Hi @louhuaidong, the V2 is out, if you want to end an event at the end of the day, you will have to set the end time at 24:00 instead of 00:00, which is more explicit and internally processed to stay on the same day.

Please have a look at the documentation from the API section > events:

> You can set an event end at 24:00 if for some reasons that's what you want, but internally the date will be set at 23:59:59 so the date stays the same instead of natural behavior of taking the next day at 00:00:00.
> When returned from emitted events, this event endDate will contain a date ending at 23:59:59.
> If you want to end an event at 00:00, you have to set 24:00 instead, to keep it to the same day you intended.

Hope it helps.

**Comment by louhuaidong** [comment]
Hi,

Thanks for the update.  I hav tried out V2.  The bahavior is just same as you and the doc described.  But in my case, it is still a little bit tricky and confused.  For example, if an event is ended at 2019-07-**27** 00:00 for some reason (like user input), I cannot transfer it to 2019-07-27 24:00, instead I have to set it to 2019-07-**26** 23:59:59.  It is still a workaround I think.  It would be cool if the vue-cal can do this automatically.

Thanks
Huaidong

**Comment by antoniandre** [comment]
I understand @louhuaidong, @arminmsg.
I leave this open and will try to handle this case internally if it's possible.

**Comment by eakenbor** [comment]
@antoniandre, I had to work around this by converting the date emitted by my date picker  to milliseconds, deduct 1 millisecond, and then convert back to a date string before saving the event to my database. I think you should solve this issue in a future version because one never knows when an emitted date could be a millisecond past the hour and this problem would re-occur.

**Comment by Twoody** [comment]
I have been experimenting with this bug and have found which options do work and which options do not work. I hope this helps those experiencing this issue:

```
  data: () => ({
    selectedDate: '2019-01-01',
    events: [
      {
        startDate: new Date('2019-01-01T00:00'),
        // Does Work
        end: '2019-01-01 24:00',

        // Does not work
        // endDate: new Date('2019-01-02T00:00'),

        // Gets converted to the same as directly above; Does not work
        // endDate: new Date('2019-01-01T24:00'),

        // Does not work
        // end: '2019-01-02 00:00', // Does not work
        title: 'FooBar'
      }
    ]
  }),

```

**Comment by antoniandre** [comment]
Hi @louhuaidong, @eakenbor, @Arminmsg, @Twoody,

I added support for events ending at `00:00` in version 2.15.0.
Demo: https://codepen.io/antoniandre/pen/MRZqaO?editors=1010
