### ISSUE TITLE
Event date manipulation in DOM event handler

### ISSUE THREAD

**Issue by DimaBDV** [antoniandre/vue-cal-v4#14]
Hello @antoniandre.
Happy New Year.

And questions.
1. Can i check date == day name

Example
`start: '2018-12-24'
if( start == 'Monday' )`

backend realization
`$date = "2018-12-22";
$week=array(0=>"воскресение","понедельник","вторник","среда","чтетверг","пятница","суббота");
$date = explode("-", $date);
return $week[date( "w", mktime(0,0,0, $date[1], $date[2], $date[0]) )];`

2. Can i get focused date

Example
`@day-focus="logEvents('day-focus', $event)"`

**Comment by antoniandre** [comment]
Hi @DimaBDV,

Happy new year to you too!
Regarding your first question, I have released a new version of vue-cal (1.12.1) to facilitate the events date manipulation in your event handler when you listen for an emitted event from vue-cal.

As now highlighted in yellow in **# Vue Cal emitted events**, to get the day of the week of a focused event you can do `event.startDate.getDay()` (number from 0 to 6 starting from Sunday).
So `event.startDate.getDay() === 1` will check if the event occurs on a Monday.

> If you plan to do more date manipulations and you are not familiar with the native javascript Date object or don't want to bother, you can always import the excellent _moment_ npm package.


Regarding your second question, what do you want to do with the focus date?
If there is no particular purpose other than getting the event date you should get the date from a focused event instead as it has a date Object and it should be more meaningful to use this instead of the cell date.

**Comment by DimaBDV** [comment]
Hi @antoniandre .
Thanks for the answer.
I need to get date focused day to use this server request.
Even if there is no event on this day.
_____________________________________________
@antoniandre 
Can I hide certain events from the event counter in the month view? (for example, hide the same class - `"hideevent"` )

**Comment by antoniandre** [comment]
Hi @DimaBDV,

I will create an event on cell day cell select soon.

For your last question, I understand what you want and that's a new and separate feature request. 
Can you please create a feature request in dedicated issue? So that the tracking of features and request is easier for us and next readers.

Thanks!

**Comment by DimaBDV** [comment]
Hi @antoniandre 
Thanks for answers. 
And.
I understood you. No problem. I will be creating new issues at others questions.

**Comment by antoniandre** [comment]
Hi @DimaBDV,

Version 1.14.0 contains a new event on day select. I also added Date objects in all the emitted events when it makes sense.
Please refer to **# Vue Cal emitted events** for the updates, and to the release notes at the bottom.

Hope it solves your issue!

**Comment by DimaBDV** [comment]
@antoniandre 
Thank you so much!!! That's what I need! I close this issue.
