### ISSUE TITLE
Overlap error with 3 simultaneous events in Version 2.2.0 (on start vue-cal)

### ISSUE THREAD

**Issue by nestormauro** [antoniandre/vue-cal-v4#150]
Hi, @antoniandre. Congratulations for release V.2. 
I was trying to test new overlap behavior with a 3 simultaneous events but one of them overlap as attachment picture shows.

![vue-cal_error](https://user-images.githubusercontent.com/23141981/62073355-2ca3f000-b206-11e9-9da9-2e7beb57601c.png)

 The script and event array are: 

`<meta charset="utf-8">
<title>vuecal demo</title>
<script src="https://unpkg.com/vue"></script>
<script src="./vuecal.umd.js"></script>

<link rel="stylesheet" href="./vuecal.css">

<div id="app" class="vuecal--green-theme">
    <vue-cal :time-cell-height="40" selected-date="2019-07-30" :dbl-click-to-navigate="false" :disable-views="['years']" default-view="week"  :time-step="30" :events="events" today-button>
    </vue-cal>
</div>
<script>
new Vue({
  components: {
    'vue-cal' : vuecal
  },
  data: () => ({
  selectedEvent: {},
  showDialog: false,
  events: [{"start":"2019-07-30 14:00", "end":"2019-07-30 18:00", "content":"Large content 1", class: "test1"},{"start":"2019-07-30 14:00","end":"2019-07-30 18:00","content":"Large content 2", class : "test2"},{"start":"2019-07-30 14:00:00","end":"2019-07-30 14:15:00","content":"Small content 1", class: "test3"},{"start":"2019-07-30 14:15:00","end":"2019-07-30 14:30:00","content":"Small content 2", class: "test3"},{"start":"2019-07-30 14:30:00","end":"2019-07-30 14:45:00","content":"Small content 3", class : "test3"}]
    }),
}).$mount('#app')
</script>
`

Thanks for your attention

**Comment by nestormauro** [comment]
Hi @antoniandre and contributors!!

I will explain a bit, the previous issue.
The error happens on assign data array on start and when eid is x_1, x_2, x_3 in this case, style left property (of the second one div event) has a value of 20% when the right value should be 33.333%


Best regards.
@nestormauro

**Comment by antoniandre** [comment]
Hi @nestormauro, thanks for your feedback.
Yes I am aware the overlapping is not perfect, and what you see here is intended as a compromise to work in most cases:
look at these 2 scenarii from the example https://antoniandre.github.io/vue-cal/#ex--edit-delete-create-events:

<img width="736" alt="Screenshot 2019-08-02 at 13 19 15" src="https://user-images.githubusercontent.com/22971289/62341963-908d2800-b528-11e9-93ce-5d5c94d11475.png">

In this one it's the same issue you have highlighted the middle event should have a 33.33% width.
But in the next case, it would create a problem if we display 33.33% then it's almost overlapping fully and not visible.

![image](https://user-images.githubusercontent.com/22971289/62342199-5bcda080-b529-11e9-96c6-db2757da6444.png)

In the second case, it would be great to keep 33.33% as width of events but place the red one in middle. Looks obvious to the eye but it's actually a lot of cases and the algorithm is very complex. Keep in mind that the more I put complexity in this algorithm the least fluid it will be while dragging, so it's a tradeoff and they are many other cases where we need to detect the empty space and distribute it across simultaneous events. 

I might re-look at it at a later stage to improve again but only if it does not impact performance.
I will close this issue for now because it's not broken but I keep in mind to try to improve it.

**Comment by nestormauro** [comment]
Hi @antoniandre thank you for your response. I understand the problem complexity, for my particular case I solving overlap using day splits.
Nice tool, thank you!!
