### ISSUE TITLE
Drag and Drop feature!

### ISSUE THREAD

**Issue by azharbuilds** [antoniandre/vue-cal-v4#174]
Hi,

Do you have any ETA when the drag and drop feature will be implemented, or if you can guide me a little bit, I can send the PR?

Thanks.

**Comment by antoniandre** [comment]
Hi @azhard4int, (and any interested **`vue-cal`** user to be part of this awesome project!)

Thanks for your interest. 
The drag and drop feature is already started in the `drag-and-drop` branch, but left aside for now for a matter of priority in the feature requests order and because of the difficulty of adapting all the code to work well with this feature and vice-versa.
If you want to help on that, I appreciate it, would be awesome.

**You can start by looking at the `index.vue` file in the `drag-and-drop` branch.
In the `onMouseMove()` function, there is a case `if (dragAnEvent._eid)` which should handle the event move at cursor coords.**
I have placed a couple of Todo lines to explain what to do in the code from there.
At the moment, I represented the move of the event on a floating blue div which is placed at cursor coords while you drag an event and then removed in `onMouseUp()`.

You will best see this blue div on the Edit, delete and create event example, the `editable-events` option needs to be true to allow drag and drop. (start dragging an event)


**So after you get familiar with the codebase, I suggest that you continue on that path and pretend the blue floatting div would be an event mirror while you drag and then on mouseUp, the event mirror disappears and the actual event is moved (so date is changed). You also need to prevent the delete button to show up.
This is the very first satisfying step.
When you complete this that's great, let's do a last code cleanup and a first PR and talk about next steps.**

If you want an overview of the milestones to integrate it fully, here it is:
- Once this is done, the next step will be to try to move the event directly in the onMouseMove() function (there will be an option to have an event mirror or not), but I am afraid it might be too slow, so we could need some refactoring.
- The third step will be to make it work with split cells, that's very straightforward.
- The fourth step I would say is to make it work with multiple-day events. That will probably be more tricky because of event segments (1 per day), but when we reach this stage we should discuss it.

Let me know if you need any help at any stage. It's important you get a good understanding of the codebase.

Thanks for any effort you do!

**Comment by azharbuilds** [comment]
Thank you for the detailed comment, I could not get back to you earlier due to our office relocation.

I'll start playing around in the coming weekend and see how it goes.

**Comment by antoniandre** [comment]
Hi @azhard4int, 
Myself too I am quite busy at the moment and I regret to have to leave vue-cal unattended for so long haha. 
But I am very excited about this feature and plan to get back to vue-cal very soon.
Anyway, don't hesitate to ask anything or get in touch by email if you prefer, you can get my email address in the package.json.

Cheers.

**Comment by cain** [comment]
We are looking to move over our calendar plugin to vue-cal and having drag n drop is a must. Please keep us updated! :)

**Comment by Nice2Work** [comment]
Hello Antoni. I am also looking forward to seeing this feature happening. I guess because all other calendars providing the same, but I have to admit, I like your calendar the best so I would like to donate more (you had a first from me a while ago) when it is ready, as I feel, if you worked for it you should get something in return for it, a pizza does not come from anything either 😁, but for me it is worth more than a pizza 😉😎

**Comment by antoniandre** [comment]
Hi @Nice2Work, 
Thanks for the feedback and enthusiasm! I appreciated your previous donation, thanks for that too!

Let me give you a little bit of context, I'd like to share about the current state of Vue Cal's project.
I split my spare time with other projects, but on Vue Cal I currently have 2 big features I am working on: recurring events, and drag and drop.

I started the recurring event first and got a quick result, so I was confident to get it done fast. 
...Until I started to integrate multiple day events and events count on year and years views. And I haven't even started to integrate the overlaps on events repetitions yet. 😞
Now that Vue Cal's codebase is quite big, everything I add must be very performant, and so far this is not, so I am not ready to release it in a near future. 

I previously left the drag and drop feature seeing it's not going to be performant enough.
But I recently came back on it with a fresh mind and a new idea, I did the basics and it's rather promising, but it will most likely not work on mobile for the first few releases.
I still believe this is the way to go though, it's way more performant than the universal way.

Now seeing that a bunch of Vue Cal users are waiting for the drag and drop, I'll try to focus on that until we can see the first results. 😉

**Comment by bjensen** [comment]
Im waiting as well for drag and drop and would be happy to make a sizeable donation to make it work :-) 

ps: Drag and drop on mobile is not important for me.

**Comment by antoniandre** [comment]
Thank you @bjensen and supporters!  :)

I made some good progress these last few days.
But to be clear touch devices won't be supported straight away, not only mobiles - that's what I meant.

___

**The important things I remain to do are:**
- handle dropping an event half in the day range
- handle splits (splitting days)
- fire DOM event on event drop
- test on Edge
- write documentation

**Won't be in the first release:**
- dragging multiple-day events
- dragging all-day events
- touch support
- snap to the closest time step in the timeline

I'll give some updates here soon!

**Comment by antoniandre** [comment]
Exciting news fellas, I am planning a pre-release end of next week!

This will be the opportunity for all to test the new feature and let me know your feedbacks.
I will create a Codepen so everybody can easily play with it.
If it is satisfying as the first stones of this feature I will do a release the following week!

___

**Updated To do:**

- Modularize the drag and drop feature (load on demand)
- handle dropping an event, half in the day range
- styles fine-tuning
- acceptance tests with all the other features
- write documentation

**Comment by cain** [comment]
@antoniandre thank you!

**Comment by antoniandre** [comment]
The first drag & drop on Vue Cal is now officially pre-released!  🎉🎉 

Check out the documentation and examples:
https://antoniandre.github.io/vue-cal/#ex--edit-delete-create-events
https://antoniandre.github.io/vue-cal/#ex--drag-and-drop-in-details
https://codepen.io/antoniandre/pen/qBdmdoV

And also check the release notes: https://antoniandre.github.io/vue-cal/#release-notes

To install the alpha version on your machine and test it on your project:
```
npm i --S vue-cal@alpha
```

Please let me know all your feedbacks, it will help me to correct things, move on and release a stable version.

Thanks for your support!

**Comment by Twoody** [comment]
@antoniandre great job! I hope I get the opportunity to try it out soon :)

**Comment by bjensen** [comment]
Looks very promissing. I will try it out very soon as well. Is there support so that I can drag and drop something from somewhere else and drop it into a weekly calendar?

My usecase is that we have a list of courses for students, so they would be somewhere else on the screen. The day is divided into sections for example 8am to 10am, 11am to 2 pm and then a user should be able to pick Math from the list and then drop it at the 8am-10am section and the event should expand to fill the entire 8am to 10am section. Im hoping I will be able to this with these drag and drop functionalities you have implemented here. 

I checked out the drag and drop things in your examples and they look good :-)

**Comment by antoniandre** [comment]
Thanks for your feedback @bjensen.
Dropping an external node is not supported right now but it shouldn't be too hard to develop and I will make it accept an HTML5 draggable DOM node.

I will work on that next after I release the stable version.
I just wait for a few other feedbacks first. :)

**Comment by cain** [comment]
@antoniandre beers on us if you're ever in Sydney :)

**Comment by bjensen** [comment]
Donated as promissed. Cant wait till you get around https://github.com/antoniandre/vue-cal/issues/174#issuecomment-593861869 :-)

**Comment by antoniandre** [comment]
Thank you @bjensen, this is greatly appreciated! :)
I am working on this feature at the moment and should release it soon.

____

**More details about where I'm at**

- I have handled the drag and drop from external event to Vue Cal and I am now handling drag and drop between 2 Vue Cal instances. This is linked with external events DnD, it will determine the final structure of the returned data on `event-drop`.

- After that I need to do some calculation when dropping an external event into Vue Cal to subtract the cursor position from the top of the event so that it lands exactly where you drop it.

- Then I will release in the alpha and will prepare to release the stable version (still not on touch devices though).

___

**Thanks everybody for your feedbacks on drag and drop and for trying the alpha! 
This is very helpful to make it more stable and awesome! 😉**

**Comment by antoniandre** [comment]
Hi @bjensen,

I have finished the external events drag & drop into Vue Cal and released in the alpha. 
 
Please refer to this example: https://antoniandre.github.io/vue-cal/#ex--external-events-drag-and-drop

`npm i --S vue-cal@alpha`

Hope it helps! Let me know your feedbacks before I release the V3 stable.

**I will release the V3 stable version end of next week!**

**Comment by antoniandre** [comment]
Hi fellas,
I released the V3 yesterday: https://antoniandre.github.io/vue-cal/#release-notes. 
The priorities have changed nowadays and I hope everybody's fine in this tough time.
But if that release can still help some users I'll be glad.

Cheer up fellas, this is not the end of the world yet! :rocket::rocket:

**Comment by antoniandre** [comment]
@ Everybody, I hope you enjoy the drag and drop feature!
I did put the touch device support in my backlog, but will start that later.
Closing the issue now!

@bjensen, I hope the external events dragging was what you were looking for!

**Comment by Nice2Work** [comment]
I know this comes as a very late reply, but I had a break of programming as I was kind of ‘overworked and burned out’ I hope you are doing well and yes I tried the new things, and they are working as promised. 

 

I looked at many things regarding calendars and one thing that always jumps out is how outlook (on the phone or online) has a very nice way of showing things and interact (I guess those guys are doing their job), especially how they ‘change times’ on an event, or how they show your events when you picked a date on the online version, is remarkable.

 

I hope you are doing well and healthy – Ronald Stevens
