### ISSUE TITLE
click month cell

### ISSUE THREAD

**Issue by Rayyangyang** [antoniandre/vue-cal-v4#187]
Can I listen for the event of clicking the month cell

**Comment by antoniandre** [comment]
Hi @Rayyangyang, yes you can.
You can try it in this example: https://antoniandre.github.io/vue-cal/#ex--emitted-events
Go to month view, clear the logs box and click a cell.

Two events are fired: `cell-click` & `cell-focus`.

So you can use like this, it's all in the documentation:

```vue
<vue-cal selected-date="2018-11-19"
         :time-from="7 * 60"
         :time-to="23 * 60"
         :disable-views="['years', 'year']"
         hide-weekends
         editable-events
         :events="events"
         @cell-click="logEvents('cell-click', $event)"
         @cell-focus="logEvents('cell-focus', $event)">
</vue-cal>
```

Hope it helps, you can reopen it it doesn't.

Cheers.

**Comment by Rayyangyang** [comment]
thank you  i have  resolve this question

**Comment by giulianimartini** [comment]
Hey @antoniandre,

I was checking this question about having cell-click event.

I am having a little issue in the month view cell click.
Is there a way to differentiate the click in the day and month view cell?

I am asking this because I have the `@cell-click` event on the vue-cal component. It fires a method to open a modal to create a calendar event (reservation).

Everything is ok when clicking the cell in the day view, but when I click the cell in the month view (with the `click-to-navigate` property assigned to vue-cal), it navigates to the week view (the expected behaviour), but also opens the modal. The issue here is that when it happens, I want to navigate to the week view and prevent from opening the modal (only in the month view).

So, is there a way to do this?

Thanks in advance.

-----

**EDIT:** I found a workaround that works pretty well for my case.

I have created another vue-cal instance only with the month view and then I related the 2 calendars according to the [sync 2 vue-cal instances](https://antoniandre.github.io/vue-cal/#ex--sync-two-calendars) documentation.

So, in the first calendar (month view), I can select the date and in the second calendar (week and day views) it changes to the selected date accordingly to the first calendar.

Then the issue about clicking the cell in the month view has been resolved, but I still want to know if there is a way to disable click only on the month view cell.

**Comment by antoniandre** [comment]
@giulianimartini,

When you set the active-view, you can use a sync modifier like so: `:active-view.sync="activeView"`.
With this sync, Vue Cal will update the variable in your component and you will know the current view at any time.
From this point, on `@cell-click` you should check the current view before triggering the action that you don't want on month view.

Hope it helps.

**Comment by giulianimartini** [comment]
Hi @antoniandre,

Thank you for this explanation. I will try it.
