### ISSUE TITLE
Can we loop time cells from 08:00 to 08:00 next day?

### ISSUE THREAD

**Issue by psengh** [antoniandre/vue-cal-v4#195]
Hi,
I have seen in doc that you can do time-from and time-to, but max value of time to is 24 * 60 so the cells stop at 24:00. Can we loop them from a given time to the same time next day, so that I can still get 24 cells ?

PS: If you don't have this feature I can raise a PR!

**Comment by antoniandre** [comment]
Hi @psengh,

`time-from` & `time-to` are used to defined the daily time range you are interested in, anything outside of this range will be hidden refer to this example https://antoniandre.github.io/vue-cal/#ex--timeline.

So if you don't set any `time-from` & `time-to` by default it will go from 00:00 to 24:00 just as a normal day.

Thanks for suggesting a PR, but I don't think it makes much sense to go over 24 hours as a day does not have more than 24 hours.
That would also cause troubles naming the day cells, what would be the title if it spans on multiple days?

If you want an event that spans on multiple days though you can already do it: https://antoniandre.github.io/vue-cal/#ex--multiple-day-events, and you can remove the `time-from` & `time-to` to see the full event on week view.

Hope it helps.

**Comment by psengh** [comment]
Hey @antoniandre,
I understood what you are trying to say. It's not a good thing to do. 

In case if you need any help in any other PR's please let me know. 
Cheers.

**Comment by antoniandre** [comment]
Thanks for your enthusiasm @psengh!
Well there's always work if you want to help on vue-cal, 
First if you have experience with #127 or #168 please have a look. Otherwise #184 seems to be the easiest issue for a start. Then #139 may be just slightly more complex.

If you start anything, please email me, (you can find my email is in the package.json file) and I will give you more instructions on what you pick.

Cheers!

**Comment by WisdomSky** [comment]
link to the PR please. I need it!
