### ISSUE TITLE
i18n not working - ChunkLoadError: Loading chunk failed

### ISSUE THREAD

**Issue by AfikDeri** [antoniandre/vue-cal-v4#196]
I've followed the documentation and imported this component into my <CalendarView> Vue component.

When I use it in my template it works great. But, once I add the `locale` prop with the `he` value (which I know this component can support Hebrew) it crashes.

Here is the way I use it
```html
<vue-cal default-view="month"
    locale="he"
    :disable-views="['years', 'year', 'week', 'day']">
</vue-cal>
```

It looks like it's trying to resolve the locale from a URL that does not exists.

Here is the error in my console.
![image](https://user-images.githubusercontent.com/17595033/67909821-506e2d80-fb89-11e9-8f0f-d7acf2a6b67a.png)

Following the stack trace it seems like the problem occurs somewhere in here:
https://github.com/antoniandre/vue-cal/blob/master/src/components/vue-cal/index.vue#L273

My Vue version is: 2.6.10

Thanks.

**Comment by antoniandre** [comment]
Hi @AfikDeri,

Did you also import the Hebrew i18n file? like in the documentation example?
https://antoniandre.github.io/vue-cal/#ex--internationalization

Here is a working codepen with localized texts: https://codepen.io/antoniandre/pen/dxXvwv,
Notice the separated load of `https://unpkg.com/vue-cal@latest/dist/i18n/zh-cn.js` (in the javascript external libs).

Let me know if that fixes your issue. Otherwise please share the full code of your example.

**Comment by AfikDeri** [comment]
You'r right. I did not import the language, that was the problem. I couldn't find it in the docs. Thanks for the reply :)

**Comment by antoniandre** [comment]
That's all good mate. 
I have updated the documentation example to make it more visible and've added the Codepen example as well.
