### ISSUE TITLE
Event specific background colors

### ISSUE THREAD

**Issue by Rjs37** [antoniandre/vue-cal-v4#209]
Apologies in advance, I already know that this is a repeat/duplicate issue, however I'm not sure if the previous advice/codepen still applies following the changes for v2.0 onwards?

I've followed the previous discussion in #115  Similar to that issue, I'm looking to pass through a background colour alongside the event. I've tried to follow the example code-pen that was mentioned there, but being fairly new to vue, I'm struggling to get something that's actually working - and I'm using the typical template syntax rather than the provided pug format.

Following between a few different examples here and there I got to the below, which renders and looks like it did before I tried to override the template, but I'm pretty sure I've put the styling in the wrong place (and probably did some other things I shouldn't)

In the code-pen I saw a div with the `event-content` class being used, but introducing that div applied the styling too late i.e. inside the div I actually want to style.

This is what I've currently got

```
<template>
    <div v-bind="$attrs">
        <vue-cal
            :hide-title-bar="true"
            :hide-view-selector="true"
            :click-to-navigate="false"
            :dblclick-to-navigate="false"
            :time-from="8 * 60"
            :time-to="19 * 60"
            :time-step="60"
            :events="events"
            @ready="fetchEvents"
            @view-change="fetchEvents"
            style="height: 500px">
            <template v-slot:event-renderer="{ event, view }" :style="{ backgroundColor: event.color }">
                <v-icon>{{ event.icon }}</v-icon>

                <div class="vuecal__event-title" v-html="event.title" />

                <div class="vuecal__event-time">
                    {{ event.start.substr(11,5) }}
                    <span>&nbsp;- {{ event.end.substr(11,5) }}</span>
                    <!---->
                </div>
            </template>
        </vue-cal>
    </div>
</template>
```

Ideally I'd also like to be able to make use of the formatTime function that I've seen being used  (rather than using substr), but so far I've not been able to use in in the above context - again probably something really simple that I've probably over-complicated.

I hope that in the future this could eventually be supported natively by the component, as it doesn't feel like event specific colouring is that unusual of a use-case, although I respect the decision that has made.

**Comment by antoniandre** [comment]
Hi @Rjs37,
The Codepen example given in #115 is still accurate I updated it after the v2 release with the new slots syntax.
https://codepen.io/antoniandre/pen/XwNdQz?editors=1010

From this Pug markup, in `template(slot="event-renderer" slot-scope="{ event, view }")`, the `template` tag does not create an html tag, so putting a style on it won't work and it will be lost.
That's why you should add a div with a class inside, like `div.event-content` so that you can apply extra not-inline CSS style.

The content-renderer does not allow you to modify the root event container `.vuecal__event`, as you say it is one level deeper, so all the style the you wanted to be on the `.vuecal__event` element should be placed on `.event-content` if it has to be dynamic style, and if you need an extra wrapper you can put it inside it.

Regarding the `formatDate` and `formatTime` methods, I have updated the Codepen to show how to do it. For information, it will use the format you have set in vue-cal by default (`twelve-hour` or not) but you can still override it if you want.

```js
formatTime(minutes) // Uses the default format.
formatTime(minutes, 'hh:mm') // You can pass the format you want.
```

And for the last thing:
> I hope that in the future this could eventually be supported natively by the component, as it doesn't feel like event specific colouring is that unusual of a use-case, although I respect the decision that has made.

It will not change in a near future, I don't think vue-cal should carry styles in the internal logic as the end user has a way to apply it as they want through renderers. If we were to add background color then why not bold, uppercase, border, box shadow, or anything that should be treated case by case outside of vue-cal. 

I hope it makes sense for you and helps understanding.

**Comment by Rjs37** [comment]
Cheers for the very quick response!

That worked a treat, in both cases. Slowly but surely understanding more about how to use Vue in the right way :+1:
