### ISSUE TITLE
Split-days value request

### ISSUE THREAD

**Issue by Csandori** [antoniandre/vue-cal-v4#224]
Hi @antoniandre!

I started to rewrite the split function of your library, but it's strongly integrated and I don't know if I can change all the options that needed. So my idea is that, the computed split property should be an object, not array, because this way we can turn it on and off the specific columns. Now, as i know, i cannot, because that way the events lose the correct column. So i introduced a value property for the array of objects "split-days".

What do you think of this idea?

Thanks!

**Comment by antoniandre** [comment]
Hi @Csandori,

I'm sorry I don't quite understand what you want to do.
I think you are talking about the `cell.vue` file, and you want to change computed `splits` to an object shape but I don't understand the purpose.

What was your use case and motivation of changing that again if I may?

Would be perfect if you can share either a reproduction link to a use case not working as you want, or source code or screenshot of a problem.

**Comment by Csandori** [comment]
So the problem is that I wanna change the split days dynamically. On the right side you can see that there are "oszlopok" (columns), where i can pick the wanted columns. If I create an event in the first column, and remove the containig column from ":split-days" then the event jumps to the next column, because it's calculated from array. That's why I recommended the object approach.

But I try to modify the source code to work like I suggest :) 

![splitdays](https://user-images.githubusercontent.com/39135389/74170761-b7da5580-4c2d-11ea-837e-b29d0fcfdc29.png)

**Comment by antoniandre** [comment]
Hi @Csandori,
That totally makes sense.
I tried a quick way in a branch, but it's not done yet and not that simple.
I've got the toggling of the splits working fine but the events will be messed up since the split indexes are recalculated.

I will check later what is the best way to continue and will let you know.
We still have 2 options:
- either move everything to Object shape as you were suggesting, but it is quite inconvenient for traversing each item in the code and requires a fair bit of refactoring, 
- or the way I started, adding a `hide` property that you can set to true or false to toggle.

Both ways will need some refactoring of the way the events are placed, as once doctor2 is hidden, doctor3 becomes the split #2.

**Comment by antoniandre** [comment]
Hi @Csandori,

I have released the ability to toggle splits in version 2.24.0.
Refer to this updated example: https://antoniandre.github.io/vue-cal/#ex--splitting-days

Hope it helps.

**Comment by Csandori** [comment]
Thank you @antoniandre!

It's incredible how fast you reply to requests!

Thanks again!
