### ISSUE TITLE
How to calculate how many events fit in a cell?

### ISSUE THREAD

**Issue by green-pigeon** [antoniandre/vue-cal-v4#228]
Hi @antoniandre 

I'm using fixed height cells on month view and I want to display only a number of events that would fit the cell (see the picture below) instead of overflowing out of it.

![image](https://user-images.githubusercontent.com/7714689/74874231-4c009700-5369-11ea-86c7-dbcbbff4c8e4.png)

Calendar cells height is vuecal__body height devided by 6 (6 rows of cells in month view). To find out how many events would fit in the cell I divide the cell height by event's height which I get from vuecal__event.
This works when I'm in month view. But when I switch from week (or day) to month and try to calculate the number on view-change, I get the height of the events in week view (which is too big). Maybe the view-change is emitted before the calendar is redrawn.

Could you give me a better idea how could I get the number of events to show?

**Comment by antoniandre** [comment]
Hi @green-pigeon,
Yes that's right, if you use `view-change`, you might have to wait for the next tick if you need some information from the DOM, like event heights.
Give a try to `this .$nextTick(() => { // what you want here. })`
Let me know if it did not work. If so, please share your code!

**Comment by antoniandre** [comment]
Btw, as this is a quite common scenario, if you get something working, please share some code for the next interested!
You have good ideas, I am sure you have an awesome app already!

**Comment by adinai** [comment]
Hello @green-pigeon, that is what I was looking for! Showing just 2-3 events and number of remaining events on the cell. Could you please share how did you do that! That would be really helpful. I believe that would help many people as  @antoniandre  said.

**Comment by antoniandre** [comment]
Hi @green-pigeon, @adinai,

Looking a bit closer at it for feasibility, I created a demo here https://codepen.io/antoniandre/pen/oNXBRqM with all the logic and styles to help you out.

But it seems that you will not be able to fully accomplish what you want, you will still be limited if you try to do exactly what you presented above:

In this case, because you want to choose which event to display or hide, you need to fully render the events list yourself which is not allowed in Vue Cal.
The reason why it's not allowed so far is that there's quite a lot of things to handle if you render the list of events yourself I found it would be too complex.

I will see if I can do something about it later, but for now I am focusing on the drag and drop feature until it's released.

In the meantime, 2 other alternatives that you can do with the current system would be:
1. each cells with events have a scrollbar
2. the cells has an overflow hidden, but the button to show more is called "show all", then it opens a popup or whatever with all the events

Hope it makes sense, otherwise you can ask me your questions.

**Comment by antoniandre** [comment]
Closing this issue as a solution is given.
If you want full control on cell please create a feature request, if other users are interested I will do something.
Thanks.
