### ISSUE TITLE
Changing class attribute of an event not reflected on view

### ISSUE THREAD

**Issue by diego-suarez** [antoniandre/vue-cal-v4#233]
Hi. Nice work sr.

Im using the library and I faced with the following problem.

I bind the events to the Vue Cal, and sometimes I want to update the data on the events. This works ok.
If, for example, I change the "title" attribute of an event it gets reflected on the view, the title changes.

But if I change the "class" attribute of the event, it doesn't get reflected on the view.
For example, defining 2 clases:

```
. new{
background-color: green;
}

.old {
background-color: blue;
}

```
If I bind the events like the follwing:

`:events="events"`

and on a component method:

```
var event = this.events[0];
event.title = "new title"; //title changes
event.class = "new"; // background does not change
```

I did inspect on the event DOM element and the class is not changed. Idk if this is a not implemented feature or a bug.

Thanks and good work!

**Comment by diego-suarez** [comment]
Sorry, I was changing the calendar event object, not the event object on the events array itself. I solved my problem changing the classes (array) attribute on the calendar object

**Comment by antoniandre** [comment]
Thanks for the feedback @diego-suarez.
That's right, once the event is passed to Vue Cal the css classes are stored in an array, so that's the form you have to use if you don't modify your array of events outside of Vue Cal.

But looking back at the code, the logic could be simplified to a simple string, and that would make things more straightforward for the user as you pointed.
Please create a Codepen of your use case or share the whole code so I can work on this scenario. :)

**Comment by antoniandre** [comment]
@diego-suarez, 
Vue Cal 3.0 you will now accept the `class` property (space separated classes).
It will not accept the `classes` array anymore.
Thanks for your suggestion.

Vue Cal 3.0 is currently in alpha version but I will release the stable version soon.

**Comment by antoniandre** [comment]
Vue Cal 3 is out now.
