### ISSUE TITLE
Event slots not rendering in month view (alpha)

### ISSUE THREAD

**Issue by max888** [antoniandre/vue-cal-v4#236]
First of all thank you for the great package and congratulations on releasing the drag/drop! It's a killer feature we've been looking forward to.

Version: 3.0.0-alpha.3
with NuxtJS

Using the event slot syntax we are trying to render custom event components on the calendar. They do not appear when in the default 'month' view. However, after switching to 'week' view the events render as expected and drag and drop works.

Switching back to month view and they still do not appear.

Here is a code example:
```
<vue-cal
    ref="vuecal"
    hide-view-selector
    hide-title-bar
    default-view="month"
    :disable-views="['years', 'year', 'day']"
    :events="events"
    editable-events
    @view-change="viewUpdated"
    @event-change="eventChanged"
    @event-drop="eventDropped"
    >
  <template v-slot:cell-content="{ cell, view }">
     <span class="vuecal__cell-date">{{ cell.content }}</span>
  </template>
 <template v-slot:event="{ event }">
    {{ event.title }}
    <!-- custom event component -->
    <calendar-event :event="event"/>
  </template>
</vue-cal>
```

Thank you for any help in solving this :)

**Comment by antoniandre** [comment]
Hi @max888, thanks for the feedback, I appreciate it.
Looking at the code you share, there's a couple of things I don't understand:
- When you say events don't appear on month view, are you talking about the events count? I assume so because you don't have the `events-on-month-view`
- If you hide both view selector and the title bar how do you switch back from week view to month view?

Regarding why the events count (if it is) don't appear on month view, it is because your custom cell renderer does not include it. 
Remember you have to add it in your renderer if you are interested in it: https://antoniandre.github.io/vue-cal/#ex--custom-title-and-cells > custom cells > big blue message.

So here is a demo of the events count:
https://codepen.io/antoniandre/pen/mdJMGxJ?editors=1010

Let me know if this is what you are looking for, and if not please fork the Codepen or share more of your code so I can better investigate the issue.

Cheers!

**Comment by max888** [comment]
Thank you very much @antoniandre , yes you are correct. Apologies I did not notice the `events-on-month-view` option. I added this prop and now I can see the events.

Due to our required design I have a separate component to call the VueCal method e.g `this.$refs.vuecal.switchView('week')`. This is how I switch views with the view selector hidden.

**Comment by antoniandre** [comment]
Ok @max888, that makes sense.
If it's all good I am closing the issue then!
