### ISSUE TITLE
Modify event in modal has no reflection on vueCal

### ISSUE THREAD

**Issue by Davekeel** [antoniandre/vue-cal-v4#237]
Hi, 
i'm trying to modify events in this way,
clicking on event  make a modal open ,  and the form within is binded via prop with the event clicked.
When i return the event modifes, like this:

this.$set(this.events, this.eventToModifyIndex, {...this.events[this.eventToModifyIndex],...$event})
($event may be like: { title: "new title", content:" modified content in modal"})
The changes doesn't effect in the VueCal vue.
is it wrong modifying the event in this way?

**Comment by antoniandre** [comment]
Hi @Davekeel,

Indeed it's not the right way for this scenario: the event that you try to modify is only a copy, stored in a "current view" subset array for performance. Vue Cal could not let you bind any event with outside variables at any time at no cost.
So this system allows to free the memory from events and related calculations when you change the current view and the event is no longer in the view.

Now what you should do is save the changes in one go on close of your dialog directly in your array of events outside of Vue Cal.
You could also have an id or index property in each of your events, so that on click of the event in Vue Cal, it will return the id or index of the event you need to update.

Hope it makes sense, let me know if you need more assistance.

**Comment by Davekeel** [comment]
thank you, your advice  resolved my issue!
