### ISSUE TITLE
Arrow-prev trouble

### ISSUE THREAD

**Issue by CristiansSans** [antoniandre/vue-cal-v4#241]
I am having a big trouble with arrow-prev, I installed the component in the correct way, but when I use in my project I get this error : 

[Vue warn]: Error in render: "TypeError: Cannot create property 'arrow-prev' on boolean 'true'"

**Comment by antoniandre** [comment]
Hi @CristiansSans, did you install the latest Vue Cal with the latest Vue? or at least Vue 2.6.1?
If yes please share your code so I can help.

**Comment by CristiansSans** [comment]
![ec3b78dc-ef40-4aca-91f6-44eb18c58461](https://user-images.githubusercontent.com/54877176/76471119-3579b880-63c8-11ea-84b2-392f643f7dc9.jpg)
![WhatsApp Image 2020-03-11 at 6 41 19 PM](https://user-images.githubusercontent.com/54877176/76471121-37dc1280-63c8-11ea-86d9-2f2898002a61.jpeg)

**Comment by antoniandre** [comment]
Hi @CristiansSans,
You have to upgrade your Vue to 2.6.7 at least, I will update the documentation where it says Vue 2.6.1.
Demo: https://codepen.io/antoniandre/pen/PoqQBeK

**Comment by CristiansSans** [comment]
Many thanks it resolved my trouble, I updated my vue version to vue 2.6.11 and it fixed it

**Comment by bpercy** [comment]
Hi. We're using 2.24.0 (fixed it to that version since we weren't ready to upgrade to 3) and this has just started happening in new builds today. I can't determine what has been changed to cause this - except is it possible that fixing the versions of all other modules in our project could have caused this? If not, what else could it be, do you think?
