### ISSUE TITLE
Remove Date prototype methods

### ISSUE THREAD

**Issue by BenAlbin** [antoniandre/vue-cal-v4#254]
As is standard practice in any language. Please can inbuilt object prototypes stop being polluted by this library. This is really bad to work with in case developers want to make their own modifications to the Date prototype in their own codebase or if changes are made in the official ECMAScript spec.

No developer should be using these Date prototype methods in their own code, because now that code is tied to a library that has no business being their Date library. So realistically these methods are only used internally.

**Comment by antoniandre** [comment]
Don't use it if you don't like it.

- The documentation says everything you need to know about these prototypes - no mystery it's like new functions, like ES6.
- Those are helper functions in a class that we all use.
- This is way more compact than using Moment.js and will satisfy most cases
- These functions have the current locale you selected pre-injected

Also, because know Javascript well, you know that you can always override functions and prototypes, so it would not be an issue if some other users would try to put their own in the same function names.

But because you say it's bad, people won't do it - so no problem whatsoever.

**Comment by antoniandre** [comment]
Also read #259, I will make it optional.
