### ISSUE TITLE
[Feature Request] Make the Date prototypes optional 

### ISSUE THREAD

**Issue by UnKnoWn-Consortium** [antoniandre/vue-cal-v4#259]
I am sure it is of good intention but I dun really think prototype pollution is a good approach to this problem. They may break things unintentionally. Can they be made optional like drag and drop or better functional?

**Comment by antoniandre** [comment]
Also look at #254.

Hi @UnKnoWn-Consortium,
I understand your concern and this is quite controversial and debatable.

I believe the concept of root pollution started a while ago when developers were putting all their variables at the root in `window` or `document` to have them global and accessible from all the JS files...

This is why we have seen many warnings about it, and I much agree with that.
I even faced the case of libs injecting conflicting variables in the past, hard to track! So I know the risk.

I found that adding the missing functions of the Date class will help developers, as long as method names are meaningful and behaviour is obvious and well documented. 

I also think that if ever by really really big chance another library is also modifying the Date class and runs concurrently with Vue Cal, and add the exact same method names, and you don't know it's happening because they don't document it, these functions would do the same thing anyway:
- `.addDays(days)`
- `.subtractDays(days)`
- `.addHours(hours)`
- `.subtractHours(hours)`
- `.addMinutes(minutes)`
- `.subtractMinutes(minutes)`
- `.getWeek()`
- `.isToday()`
- `.isLeapYear()`

And for the formatters `.format(format)` & `.formatTime(format)`, it would also be expected to format and output.


But I will make this optional as you suggest, so it will be the user's call to use it or not.

**Comment by antoniandre** [comment]
Hi @UnKnoWn-Consortium, this is now possible in version 3.1 using the option `disable-date-prototypes`.
Also check the release notes: https://antoniandre.github.io/vue-cal/#release-notes
