### ISSUE TITLE
Add releae notes into the github releases

### ISSUE THREAD

**Issue by onomojo** [antoniandre/vue-cal-v4#295]
Its hard to know what's changed just from looking at the releases on github. I click releases https://github.com/antoniandre/vue-cal/releases and just see numbers. I know you have the release notes over here on the other doc site https://antoniandre.github.io/vue-cal/#release-notes but it'd be helpful to have them on the github releases too since its kind of the normal place where people look for release notes on github projects.

**Comment by onomojo** [comment]
So some context, I'm interested in the recurring event feature under development so I've been watching release notes regularly. I was just finding it annoying having to hunt them down each time.

**Comment by antoniandre** [comment]
Hi @onomojo, 
I see, you are indeed looking for the feature that has been pending forever. lol
If that can help, you can subscribe to the #55 feature request thread, I will post in it when it is ready or there is anything new to say on it.

Regarding releases in Github, I would release detailed versions on Github with pleasure if I find a convenient single line command, just like I do `git push tag`. But looking at releases documentation it's quite tedious.

I am investigating on third party libs that automate releases. like this one https://github.com/release-it/release-it/issues/674

If you know an easy one let me know, meantime I wait for the answer on release-it.
 
Also for info, if in the end I don't find an easy way and it turns out to be too tedious, I simply will not do it - the release notes are already available in one place at least. And I'd rather spend my time doing this feature!

**Comment by onomojo** [comment]
I don't know anything off hand an a quick search just gives me things that look like a pain to get going. Fair enough. Closing
