### ISSUE TITLE
 delete and modify events

### ISSUE THREAD

**Issue by mynhidwotz** [antoniandre/vue-cal-v4#3]
Is there any way to delete or modify specific events in the calendar?

**Comment by antoniandre** [comment]
Hi @mynhidwotz, I am currently working on the events full reactivity, so you can change anything in your array of events and it will update into vue-cal.
Apart from that, you can already modify the duration of events by dragging the bottom of the event. (v. 1.1.0).
After event reactivity, I will add a delete feature on events and implement the draggability.

**Comment by mynhidwotz** [comment]
ok, thank you 
nice work!

**Comment by antoniandre** [comment]
Thank you,
I created a branch that I am working on for the events reactivity, I will ping you here when I am done with it.

**Comment by antoniandre** [comment]
Hi @mynhidwotz, the event deletion feature is now released!
By the way, I previously said you would be able to delete events from your array of events (outside of Vue Cal) and have the changes updated automatically within Vue Cal. This is now possible. 
**But due to reactivity, if you do so all the events and their data will be reloaded in Vue Cal after a change in the external array. You could possibly lose your changes in Vue Cal**.

The next features will be event dragging, then event creation and I will add an example how to export the modified events to use them out of Vue Cal.

PS: I have added 2 new texts for event creation and deletion. It would be awesome if you could update the sp.json file!

**Comment by mynhidwotz** [comment]
excellent news, in a moment I update the translation in Spanish

**Comment by bilics** [comment]
Hi! I am sorry but I haven't found this in the documentation: 

Is it possible to detect click for a particular event ? 

I would like to manage/sync edit's and deletion's on the backend for instance.

thanks!

**Comment by antoniandre** [comment]
Hi @mynhidwotz, sorry but for now it is not possible. I still have a few things to redesign, now the component is getting bigger, before I move on to the next features.
But I will definitely emit events with parameters in a near release, so that you can listen to them and perform tasks outside of vue-cal easily.

I will let you know here.
Cheers!

**Comment by bilics** [comment]
Thanks!

**Comment by antoniandre** [comment]
Hi @bilics, 
In version 1.7.0 you can now listen to vue-cal emitted events to trigger actions when your events are updated. Have a look at the example **# Vue Cal emitted events**.
I hope that it will unlock a few things!

**Comment by bilics** [comment]
Thanks @antoniandre !

**Comment by bribar** [comment]
@antoniandre is updating events still a WIP?
