### ISSUE TITLE
on-event-click requires 2 taps on mobile devices

### ISSUE THREAD

**Issue by NyxCode** [antoniandre/vue-cal-v4#322]
`on-event-click` is only fired when an event is tapped twice on mobile devices.
This happens in Chrome on Android and in the latest Safari on iOS.

**Comment by NyxCode** [comment]
Pretty dealbreaking for me right now. Doesn't work on the doc page, too.
Just go [here](https://antoniandre.github.io/vue-cal/#ex--open-dialog-on-event-click) on your phone and try tapping on the events.

**Comment by antoniandre** [comment]
Thanks for reporting @NyxCode, sorry for the delay. I'll let you know when this is fixed.

**Comment by antoniandre** [comment]
Hi @NyxCode, This should now be fixed in version 3.6.5.
I can see it is fixed on the example of the documentation. 

I also added a 30px move threshold when tapping the event so that a tap and drag will not fire the event click.
https://antoniandre.github.io/vue-cal/#release-notes

Hope it helps.

If it doesn't please reopen the issue.

**Comment by NyxCode** [comment]
Awesome, thank you!

**Comment by antoniandre** [comment]
Great if it's fixed! 
Sorry I did not see this issue initially and I am always quite busy. haha
