### ISSUE TITLE
Vue 3

### ISSUE THREAD

**Issue by rsuurd** [antoniandre/vue-cal-v4#336]
Is there any work being done to support vue 3?

Currently i am using vue 3.0.0-rc11 and am getting some console errors:

```
vue-cal.js:5412 Uncaught TypeError: Cannot read property '_c' of undefined
    at Proxy.render (vue-cal.js:5412)
    at renderComponentRoot (runtime-dom.esm-bundler-70c5313f.js:1794)
    at componentEffect (runtime-dom.esm-bundler-70c5313f.js:5578)
    at reactiveEffect (runtime-dom.esm-bundler-70c5313f.js:343)
    at effect (runtime-dom.esm-bundler-70c5313f.js:318)
    at setupRenderEffect (runtime-dom.esm-bundler-70c5313f.js:5561)
    at mountComponent (runtime-dom.esm-bundler-70c5313f.js:5519)
    at processComponent (runtime-dom.esm-bundler-70c5313f.js:5479)
    at patch (runtime-dom.esm-bundler-70c5313f.js:5101)
    at componentEffect (runtime-dom.esm-bundler-70c5313f.js:5596)
```

**Comment by antoniandre** [comment]
Hi @rsuurd,
I'll have a look soon, for now it is not supported.

**Comment by rsuurd** [comment]
cool, thanks for your quick reply :)

**Comment by antoniandre** [comment]
Hi @rsuurd, 
Vue 3 has officially be released a few hours ago, it's still a very early stage to use it.
Even if Vue itself is now ok to go on prod environments, most of the libraries don't support Vue 3 yet, Vuetify for instance.
So IMHO it's not ready to ship just yet.

That being said, I spent some time today on moving Vue Cal to Vue 3.
I created a branch https://github.com/antoniandre/vue-cal/compare/next and did  what I could, like the straightforward migration steps and some more, but it's not fully working yet.

There are some complex patterns in Vue Cal which don't work out of the box in Vue 3 - mainly due to the different way the reactivity is handled with internal proxies.

I will keep this branch open until it's easier to find documentation on how to get everything working as in Vue 2.

In the meantime, if you or anyone want to contribute on this branch please feel free, you can also ask me some questions about the codebase if that helps.

Cheers.

**Comment by antoniandre** [comment]
Hi @rsuurd,
I have made good progress on supporting Vue 3, I just released the first official Vue Cal for Vue 3!

To install, `npm i vue-cal@next`

Let me know if you find any problem. Hope it helps.

**Comment by antoniandre** [comment]
Vue 3 is now supported, so I am closing the issue.
Please reopen if you see any problem.
