### ISSUE TITLE
One month Vue instance

### ISSUE THREAD

**Issue by xiscohv** [antoniandre/vue-cal-v4#350]
This could be a cool feature to improve the rendering of the 12 Vue Cal in the year view. So each calendar would have only one month and not 12 for each calendar.

**Comment by rubjo** [comment]
Please read the documentation and clarify:
https://antoniandre.github.io/vue-cal/#examples
https://codepen.io/antoniandre/pen/jOOmxzo

?

**Comment by antoniandre** [comment]
Hi @xiscohv thanks for the suggestion. It's not very clear to me, but I think you would like to have the month view of a whole year at a time with events shown on month view. 
So it's almost like the Codepen @rubjo quoted, but with events, if that's what you mean?

If that is, it's already possible separately like on the Codepen, but not within Vue Cal's codebase because this would be too slow to render and recalculate all the events at once in addition to all the checks and views rendering itself.

Please reopen if that is not what you meant or if you want to clarify the need. 
Cheers.
