### ISSUE TITLE
assign custom data to event object created by vue-cal event.

### ISSUE THREAD

**Issue by nyash** [antoniandre/vue-cal-v4#358]
Hello,
 
Consider this sample that makes use of 2 events: `event-drag-create` and `event-title-change`:

```
        <vue-cal   
            v-on:event-title-change="onEventTitleChange"
            v-on:event-drag-create="onEventDragCreate"  
            :editable-events="{ title: true, drag: true, resize: true, delete: false, create: true }"
            :events="events"></vue-cal>
```

```
new Vue({
    el: "#page",
    data() {
        return {
            events: [{
                start: '2018-11-20 14:00',
                end: '2018-11-20 18:00',
                title: 'Need to go shopping',
                data: {id: 1}
            }]
        }
    },
    methods: { 
        async onEventDragCreate(event) {
            let id = await this.api.createEvent(event.start, event.end); /* this returns the assigned id from the database */
            event.data = {id: id};
            return event;
        },
        async onEventTitleChange(event) {
            await this.api.changeTitle(event.data.id, event.title); //error! event.data.id is undefined
        }
    }
});
```

1) When an event is created via dragging, `onEventDragCreate` is called. It receives an event object as a parameter. I persist it in the database and assign a custom data object to the event containing the id.

2) When I click on the same event in the calendar to change the title, `onEventTitleChange` is called, but an error is thrown. `event.data` object does not exist.

How could I solve this? Apparently the custom `data` object that I assign in the `onEventDragCreate` is not reflected in the event object in the `onEventTitleChange` callback.

Thanks!

**Comment by antoniandre** [comment]
Hi @nyash,

In your case, the modification you are doing on the event in `onEventDragCreate` is not passed back to Vue Cal.
You could modify the event in the external array if you want, the one in your data > `events`.

Another way, if you want to directly modify the event inside Vue Cal after it's been created, you also have to provide a custom function to execute when Vue Cal creates the event: `:on-event-create="onEventCreate"`.

This is because from the emitted event `@event-drag-create` there is no way to pass back the modified event to Vue Cal.

So `onEventCreate` will provide you with the current event that you can modify and return back to Vue Cal from within this function.

You can check the closest example of your use case in https://antoniandre.github.io/vue-cal/#ex--other-event-creation-methods > case 3 - last example.

If you feel like the creation is not clear, you should also re-read the whole creations examples section :https://antoniandre.github.io/vue-cal/#ex--other-event-creation-methods

Hope it helps! :)

**Comment by nyash** [comment]
hi @antoniandre 
 
`You could modify the event in the external array if you want, the one in your data > events`

This is what I was trying at first, but no events were being added to my external array in the Vue ViewModel. So I was trying other means of achieving the same result.

Now that I came back to the code after a while now I see where the mistake was.... Embarassingly I had an empty `:on-event-create="onEventCreate"` callback for debug purposes. (It was not returning the newly created event, so nothing was being added to the external array). 

Now after fixing it, events are being added to the external array and I can modify them there.

Thanks! :-)

**Comment by nyash** [comment]
hi @antoniandre

This is how I have eventually solved the problem (by keeping track a map of the internal _eid property):

`new Vue({
    el: "#page",
    data() {
        return {
            eid2Id: {},
            events: [{
                start: '2018-11-20 14:00',
                end: '2018-11-20 18:00',
                title: 'Need to go shopping',
                data: {id: 1}
            }]
        }
    },
    methods: { 
        getEventId(event) {
        	if (event.data) 
        		return event.data.id;
        	else
        		return this.eid2Id[event._eid];
        }
        async onEventDragCreate(event) {
            let id = await this.api.createEvent(event.start, event.end); /* this returns the assigned id from the database */
            this.eid2Id[event._eid] = id;
            return event;
        },
        async onEventTitleChange(event) {
            let id = this.getEventId(event);
            await this.api.changeTitle(id, event.title); 
        }
    }
});`

Thanks!

**Comment by nyash** [comment]
@antoniandre

Thanks!
