### ISSUE TITLE
day letters are offset from day numbers

### ISSUE THREAD

**Issue by dansgithubuser** [antoniandre/vue-cal-v4#397]
![image](https://user-images.githubusercontent.com/1649921/115047058-27894780-9ea6-11eb-8008-6a173b1cfa40.png)
(screenshot from https://antoniandre.github.io/vue-cal/, ubuntu, firefox (same result with chrome))

```
.vuecal__weekdays-headings, .vuecal__all-day {
    padding-right: 12px;
 ```
 
 I think coming from here: https://github.com/antoniandre/vue-cal/blob/973bf2852decfb8d2cefa35695766aee860ad765/src/vue-cal/index.vue#L1180

So maybe it's related to https://github.com/antoniandre/vue-cal/issues/221 ?

**Comment by antoniandre** [comment]
Thanks for reporting @dansgithubuser, and sorry for late reply.
Indeed, I found this is happening on views without time when the operating system sets the scrollbars as fixed - so I never saw it. 

<img width="524" alt="image" src="https://user-images.githubusercontent.com/22971289/187039263-be3d3a77-b08e-4f15-8e46-ec347c2504b6.png">

Now fixed in version 4.4.3 :)
But you probably moved on 🤷‍♂️
