### ISSUE TITLE
fixed header (vertical only) with sticky split labels that scrolls horizontally 

### ISSUE THREAD

**Issue by CavalcanteLeo** [antoniandre/vue-cal-v4#419]
Is there a way to fix vertically the split labels on top no matter where the Y scroll is.

split label is showing, no scroll:
<img width="440" alt="Captura de Tela 2021-07-03 às 03 58 24" src="https://user-images.githubusercontent.com/1735944/124346081-2fa67880-dbb3-11eb-85ce-f53dc7f2f901.png">

split label is NOT showing, scrolled down, but there is overflow-x:
<img width="440" alt="Captura de Tela 2021-07-03 às 03 58 34" src="https://user-images.githubusercontent.com/1735944/124346079-2d441e80-dbb3-11eb-863f-7f4be8d50706.png">

split label is showing, scrolled, but there is no overflow-x:
<img width="440" alt="Captura de Tela 2021-07-03 às 03 59 17" src="https://user-images.githubusercontent.com/1735944/124346080-2f0de200-dbb3-11eb-8db8-5ee1c2ed9d01.png">

I must keep showing Mom, Dad, kid 1, kid 2 and kid 3 on the top, always, but need also to scroll horizontally 

i tried with position: sticky, but i've not succeed. If the HTML was structured in another way, `position: sticky` would work

the closest I get is:

```js
const calendar = document.querySelector('#beauty-calendar .vuecal__bg')
      calendar.addEventListener('scroll', function () {
        const splits = document.querySelectorAll('.vuecal__cell-split')
        for (const split of splits) {
          split.style.top = '10px'
          split.style.position = 'absolute'
        }
      })
 ```

but not smooth at all

**Comment by CavalcanteLeo** [comment]
@antoniandre Could you give me a hand?

**Comment by rubjo** [comment]
Hi!

Pure usage-related questions are probably better to post on Stack Overflow than as an issue in this repo.

In any case, a minimal reproduction demonstrating the issue using CodePen, CodeSandbox or similar is needed to be able to help you.

**Comment by antoniandre** [comment]
Hi @CavalcanteLeo,
Technically, with this complex HTML structure there is no way to do it with pure CSS AFAIK, and that's why it's not there.
But your approach is fine I think (I'd like to see it running to be sure to follow you). 
If not smooth you can already cache some DOM lookups which is very heavy process for a scroll listener which triggers hundred times and must be extremely light.

Just save the DOM collection `document.querySelectorAll('.vuecal__cell-split')` outside the event listener, that will already be much smoother. For that, in your Vue component, just declare the splitsCollection above the export default, and update the collection on each view change. Then in the scroll listener you can use your cached array.
This is theory, and you might have moved on anyway. But if you still need help please reopen.
