### ISSUE TITLE
Bug with ending of event

### ISSUE THREAD

**Issue by HlukhovYe** [antoniandre/vue-cal-v4#482]
Please, fix bug with ending of event bcz when I create event, for example, from 02:00 to 03:00, in console event show me {start: 02:00, end: 02:01}, I checked, your docs has the same problem (Events-related log)
![image](https://user-images.githubusercontent.com/76591663/169598800-cb281b44-0523-4b04-950c-dd6d8f448e2a.png)

**Comment by supersophisticated22** [comment]
+1, is there a work around?

**Comment by antoniandre** [comment]
Hi @zlodey509, @supersophisticated22,
I'm not sure I understand the issue.

In the documentation in the logs box at https://antoniandre.github.io/vue-cal/#ex--emitted-events, when you click a cell or drag an event end, it will log a time that includes a timezone. this is because the events are JSON stringified in that logs box.

In this screenshot, I resized the bottom of the event, then it logs `12:11` but the `endTimeMinutes` is correct and if you `console.log()` it will show up correctly.

<img width="782" alt="Screenshot 2022-08-27 at 22 29 30" src="https://user-images.githubusercontent.com/22971289/187047052-e215e5b0-9629-4c39-ad12-fa9e429d5842.png">

If not solved, please reopen with a clear description of the problem and a reproduction where I can see the issue. :)
