### ISSUE TITLE
Updating Event Reactivity

### ISSUE THREAD

**Issue by bribar** [antoniandre/vue-cal-v4#51]
Hey @antoniandre nice plugin!

I referenced this https://github.com/antoniandre/vue-cal/issues/3 but I think its a different issue. Or is it the same and I'm missing something?

It doesn't seem like events are reactive, like when updating an event(s)...

https://jsfiddle.net/bribar/d2nv7Lue/46/
Clicking UPDATE updates the events as seen in console. Then if you click the "Need to go shopping" which should be "Dude Brah" but isn't. View doesn't update either.

Am I correct? If so, is this on the roadmap?

**Comment by antoniandre** [comment]
Hi @bribar,
Thanks for your feedback.
Well this is supposed to be possible like shown in documentation here: https://antoniandre.github.io/vue-cal/#ex--modifying-events-from-outside

According to your example the events props are not reactive, which is maybe a regression that I have introduced while refactoring. I will have a look into what causes this.

But anyway, there is also another way to update your event, which is even better since it won't trigger a full refresh of all the events: 
in this fiddle https://jsfiddle.net/ajuLsdqh/2/, as you are passed the clicked event you can just update its props from there:

```js
onEventClick (event, e) {
    event.title = 'Dude Brah'
    event.start = '2019-02-20 12:30'
    event.startTimeMinutes = 12.5 * 60 // This is actually necessary to change the time, won't be in the future. 
}
```

Hope it helps.

**Comment by bribar** [comment]
That doesn't seem very practical to edit the event when you click the event but I see what your saying.
Any idea how far out this might be fixed?

Thanks!

**Comment by antoniandre** [comment]
Hi @bribar,
Fixed in version 1.35.3. you can retest your Fiddle (clear cache) and call your `updateEvent` method.

> That doesn't seem very practical

haha from your test I thought that's what you wanted.

**Comment by bribar** [comment]
Awesome! @antoniandre 

I was referring to the onEventClick option didn't seem practical because its static. I'm looking for a more dynamic way like what you just fixed. To me onEventClick would be for clicking the event to edit, loading the event data into a modal or something, changing it and then saving. 

Anyways, thanks for your hard work!

**Comment by bribar** [comment]
@antoniandre after updating I get this error. It was all working great prior to update. Didn't change anything.

[Vue warn]: Error in render: "TypeError: Cannot create property 'events-count-month-view' on boolean 'true'"

If i revert to 1.35.0 vue-cal works

**Comment by antoniandre** [comment]
@bribar, 
interesting... Can you share your code please?

**Comment by bribar** [comment]
Sorry @antoniandre must have been a bad install. I re-tried npm install vue-cal and no errors.

False alarm :(

**Comment by antoniandre** [comment]
No worries, glad it is still fixed! 👌
