### ISSUE TITLE
vue-cal 3.9 works and vue-cal 3.11 has an issue with drag-and-drop.js not existing

### ISSUE THREAD

**Issue by mikebski** [antoniandre/vue-cal-v4#517]
When I ls node_modules/vue-cal/dist I have drag-and-drop.js

When I upgrade to vue-cal 3.11, I have the following in node_modules/vue-cal/dist (note there is not a drag-and-drop.js):

drag-and-drop.amd.js    drag-and-drop.es.js     vue-cal.amd.js          vue-cal.es.js           vuecal.css
drag-and-drop.cjs.js    i18n                    vue-cal.cjs.js          vue-cal.iife.js

When I build, I get this error:

This dependency was not found:

* vue-cal/dist/drag-and-drop.js in ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/events/Calendar.vue?vue&type=script&lang=js&

Any idea why 

1) vue-cal does not have a vanilla drag-and-drop.js in the new version 
and 2) how can I use the new version?

Stack overflow question here: https://stackoverflow.com/questions/74505412/vue-cal-3-9-works-and-vue-cal-3-11-has-an-issue-with-drag-and-drop-js-not-existi

**Comment by antoniandre** [comment]
Hi @mikebski,

Here are 2 working demos of Vue Cal with drag & drop:
- running on Vue Cal 3.10.4: https://stackblitz.com/edit/vuecal-vue2-7jjee8?file=src%2FApp.vue
- running on Vue Cal 3.11.0: https://stackblitz.com/edit/vuecal-vue2-uzsas3?file=src%2FApp.vue,package.json

Note that since 3.11.0, the drag and drop module is loaded on demand (lazy-loaded) without you to externally load it.
As stated in the drag and drop example orange callout: https://antoniandre.github.io/vue-cal/#ex--drag-and-drop

It can also be helpful to explore the vue-cal dist folder available files, directly in node_modules/vue-cal/dist, when you have a doubt if a file is there or not. :)

Hope it helps, please reopen if not solved.

**Comment by vesper8** [comment]
@antoniandre I also ran into this breaking change. Been using 3.10.5 for a very long time. Is there a changelog between 3.10.5 and 3.11.0?
