### ISSUE TITLE
Drag support

### ISSUE THREAD

**Issue by davidgraeff** [antoniandre/vue-cal-v4#52]
I have checked your drag support branch.
Is there a reason that you don't build up on the [html drag and drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API)?

tl;dr

That would only require a "draggable" attribute on a vuecal__event.
* Instead of a onMouseMove, you work with the `dragstart` event.
* On your vuecal__cell you just need to react on the "drop" event.
* To make the vuecal__cell a valid drop zone, you implement the "dragover" event handler.

This works perfectly in my private repo as long as a cell is not editable. In your current code you do a lot of preventDefault, which prevents the drag event to happen if the cell is editable.

**Comment by antoniandre** [comment]
Hi @davidgraeff,
Thank you for your ideas and tips, I did not spend long on this feature yet.
I try to have a stable "read & display events" calendar with all the requested features first.

This  API looks great, but apparently it's not currently supported on android https://caniuse.com/#feat=dragndrop

I don't think it will be very hard to do the drag and drop as I already did the resizing events by click and drag, it's only a matter of time because I am busy. 😅

**Comment by davidgraeff** [comment]
If you aim for mobile browsers, then the D&D specification is not very helpful indeed. It is exclusively for desktop browsers as its concept didn't incorporate touch events. Closing this for now, and I'm looking forward to your solution.
