### ISSUE TITLE
Hard to contribute: Giant index.vue

### ISSUE THREAD

**Issue by davidgraeff** [antoniandre/vue-cal-v4#53]
It is really hard to contribute to your project, because of your giant index.vue component (1.7k lines).

I suggest to
1. move the style into its own scss file and let the build system figure that out.
2. and to move the headerbar out of index.vue into its own component.

There are probably more ways to split the file up, but those are the low hanging fruits.

Cheers

**Comment by antoniandre** [comment]
Hi @davidgraeff,
Thanks for your interest into contributing!

As I add features the code base is getting bigger and bigger and I agree it would be nice to split it into multiple files now. I actually had this in mind for a while.
But there is a tradeoff: code will be more complex and not significantly shorter in the main index.
The reason for that:
- some logic needs to be shared across the different components and remain in the index
- increased complexity because of nested slots, passing down props, calling parent methods

I have split the header into a different file in the `refactoring` branch I will think it over to see what can be improved and moved but if you want to have a look and give me some feedbacks, please do so!

**Comment by davidgraeff** [comment]
> some logic needs to be shared across the different components

Use ES6 modules and move utility methods into own files. The build system will care about joining everything. The "updateMutableEvents" method is a good candidate for example. Basically all methods that are not "reactive".

> if you want to have a look and give me some feedbacks

Sounds promising, I'll have a look.

> As I add features the code base is getting bigger and bigger

I have seen your ToDo list. If you are done with that, this component will be the most complete component for Vue that I've seen so far. But don't do the charts.js mistake, they are now in the second year of refactoring, from their original one-file monstrosity.

Vue provides you with a lot of tools to create small re-usable pieces. You can design (additional) features as Mixins for example (like Drag&Drop, Editable-cells, different View modes) and allow the user to add Mixins as he needs them. That way an ES6 ready build system will tree-shake your component for smaller file sizes (your component with all its features, non-gzipped is close to 100kb).

Cheers, David

**Comment by antoniandre** [comment]
Hi @davidgraeff, 
I did a good refactoring and will stop here for the big part. Now merged into master.
I will keep improving as I develop new features but I am closing the refactoring branch.

- Header is moved into a new component
- Weekday headings is moved into a new component
- Styles are split where it belongs into new components
- Some of the logic is moved into the new components
- The main big file is now down to less than 900 lines

I will keep in mind modularising the features into  mixins, but it is not the priority now.
Thanks for your advice!

**Comment by davidgraeff** [comment]
Thanks :)
