### ISSUE TITLE
"can't assign to property "events-count-month-view" on true: not an object"

### ISSUE THREAD

**Issue by karelbyte** [antoniandre/vue-cal-v4#57]
Hello, for no apparent reason, because I have not made any changes, I began to arrogate this error, even though I'm not working with anything like this https://antoniandre.github.io/vue-cal/#ex--events- indicators-on-month-view, can any suggestion be this ?, I show you my component configuration 
<vue-cal
                    :time="false"
                    style="height: 95vh"
                    locale="es"
                    default-view="month"
                    class="vuecal--green-theme"
                    :events="datas"
                    events-on-month-view="true"
                    class="vuecal--full-height-delete"
                    :on-event-click="onEventClick"
                    @day-focus="clickDay"

            ></vue-cal>

**Comment by DuredhelFinceleb** [comment]
I have the same issue. I'm not sure that this is vue-cal related though
I'm too recent in the node.js world to know if my vue package was updated (at least nuxt wasn't) but I've fixed the issue by modifying my node_modules/vue/dist/vue.runtime.esm.js into funtion resolveScopedSlots line 2717:
res = res || {};
by
res = (res && typeof res=="object") ? res : {}

There are tons of vue files with that code (vue., vue.ems, vue.common, resolve-slots, basic, buld, etc.), I've got no clue if they should all be modified, just to sure I've changed them all. 'vue.runtime.esm.js' is the one that did the trick for me when I reloaded my page.

Hope that helps

**Comment by karelbyte** [comment]
thanks for the comments, the detail is that I do not use node_modules my component load is like this
<head>
   ...
   <script src = "https://unpkg.com/vue"> </ script>
   <script src = "https://unpkg.com/vue-cal"> </ script>
   <link href = "https://unpkg.com/vue-cal/dist/vuecal.css" rel = "stylesheet">
</ head>, I would like to be able to solve it as you tell me but I think there is no way, unless you bring me the library from vue to local and modify! Do you think that you can solve it?

**Comment by DuredhelFinceleb** [comment]
download the link https://unpkg.com/vue with your bowser / curl / wget / your favorite tool
the link is a redirect to https://unpkg.com/vue@2.6.7/dist/vue.js
Save the file and edit it. Search the line 
res = res || { $stable: !hasDynamicKeys };
and replace it with
res = (res && typeof res=="object") ? res : { $stable: !hasDynamicKeys };
An then put the modified file on your server. Your script tag would something like
<script src = "https://myserver/vue.js">
And that should to the trick. Note that I cannot be sure this will work, my knowledge of Vue is limited and I've never used it like you do. Moreover this method means that you have to use your modified copy as soon as you point your script tag back to unpkg.com, you'll have the problem again

In any case, note that this has some visual impact on the month view, the no even slot does not appear any more. And it might be a vue-cal bug after all since your version of Vue is more recent than mine and you still have the problem. Unless you're in a hurry you might want to wait for a fix

**Comment by antoniandre** [comment]
Hi @karelbyte, @DuredhelFinceleb,

There is indeed a bug I am investigating on. Sorry for that.
Started to break between version 1.35.1 & 1.35.3. As it works in my environment and my documentation I suspect it is a package dependency update causing the issue.

Will let you know soon.

**Comment by antoniandre** [comment]
Ok, I don't know what happened lately but I just published a new version and the issue is gone.
Please use version 1.38.1 and let me know if you still have issues.

**Comment by DuredhelFinceleb** [comment]
the issue is gone with 1.38.1 👍

**Comment by karelbyte** [comment]
perfect, thanks for fixing the problem fast :)

**Comment by antoniandre** [comment]
FYI if this issue comes back: It seems that it is a bug from Vue: https://github.com/vuejs/vue-hot-reload-api/issues/73
here: https://github.com/vuejs/vue/commit/7ec4627902020cccd7b3f4fbc63e1b0d6b9798cd
