### ISSUE TITLE
Please mark this project as deprecated

### ISSUE THREAD

**Issue by MedLabs** [antoniandre/vue-cal-v4#573]
Since vue-cal is not maintained anymore, it's good to let people know that they're gonna use it as it is now and no more features or bug fixes will be added anymore...
BTW is there any good fork of vue-cal ?

**Comment by devstack-be** [comment]
I m currently working on a fork and refactoring it without pug, with composition api and tailwind styles

**Comment by moulcode** [comment]
Subject: Re: [antoniandre/vue-cal] Please mark this project as deprecated
(Issue #573)

Hi there,

Thank you for the update on your work. I appreciate your efforts in
refactoring the project.

Best regards,
Abderrazzak Ouahib

**Comment by antoniandre** [comment]
Hi there, atm the project is not actively maintained and the codebase hasn't been changed in nearly 2 years.
There are some PRs that I did not have enough time to sort because most of the PRs are improving or fixing 1 thing without taking in account other aspects and they can't just be merged like that without refactoring.
If things go as planned, I'll spend time on Vue Cal again this summer, and will refactor everything for Vue 3 only, remove compatibility with Vue 2 and will most likely change the HTML structure as well in order to welcome new features like horizontal layout and panning.
For now I'm adding a message in the main readme that this is as is for now but not dead. :)

**Comment by antoniandre** [comment]
I've already started the v5 structure in a branch
