### ISSUE TITLE
Create event at cursor position - on cell click and hold

### ISSUE THREAD

**Issue by ArjenSwBase** [antoniandre/vue-cal-v4#62]
Hello @antoniandre,

I am looking for functionality that does the following:
When double clicking on a day (In week view) I want an event to trigger that tells me the date and time where you clicked. Currently the @day-focus event gives you a date but not a time, its also only double click. The time doesn't have to be minute perfect, can be rounded to the nearest 15 minutes or so.

Could you make something like that or do you have any idea how I could do that with the current events?

**Comment by antoniandre** [comment]
Hi @ArjenSwBase, 
Are you looking for this feature in order to create an event?
If so I am very close to releasing the event creation feature where you click and hold a cell and it will create an event starting at cursor position.

If this is not what you are looking for, I can help you do the calculation to get the exact time from the cursor position, this is what I do here: https://github.com/antoniandre/vue-cal/blob/48eac0a5476f605f33dc55a8939ab4210c2a30da/src/components/vue-cal/index.vue#L636

**Comment by ArjenSwBase** [comment]
Hi! Sorry for the late reply,

Yes, this is indeed for event creation. But the event creation in our system is in a new page. 
With the event creation feature you are releasing soon; could you make it so that there is a new event I can use for when the person clicks and holds?

**Comment by antoniandre** [comment]
Hi @ArjenSwBase, 
I am now going through tests with this feature.
This will indeed create a calendar event at cursor position on click and hold of a cell as well as emit a DOM event that you can listen to.
This emitted event passes the calendar event object so you can modify it and pass it back.
Feel free to test it on `create-event-feature` branch (Editable / deletable events example).

Will let you know when stable and released.

**Comment by ArjenSwBase** [comment]
Hey @antoniandre 

I finally had some time to checkout the create-event-feature branch. And I couldn't figure out how to trigger the create event events.

**Comment by ArjenSwBase** [comment]
Hey @antoniandre 
I figured it out! I had to put events-editable to true.

Anyway, I found some things you might wanna look at before releasing this feature:

`end: "2019-03-2712:6"`
`endTime: "12:6"`

The formats are not really how you would want them. (Same counts for start, startTime)

This is how you probably would want it.
`end: "2019-03-27 12:06"`
`endTime: "12:06"`


endDate is also seen as an invalid Date. but that would probably be fixed if you fix above formats.

**Comment by antoniandre** [comment]
Great thanks for pointing it out, I will have a look and fix this. 
I also found a bug that delays the release. 
But in the meantime, the best example to try to see the creation behavior is this one: `#ex--editable-deletable-events` where I create a modal to set the event title content and class.

**Comment by antoniandre** [comment]
Hi @ArjenSwBase, the event creation feature is out!
Please refer to these examples:
- https://antoniandre.github.io/vue-cal/#ex--edit-delete-create-events
- https://antoniandre.github.io/vue-cal/#ex--more-advanced-event-creation

Please close the issue if working as expected.

**Comment by anhnguyenpku** [comment]
Hi @ArjenSwBase, the event creation feature is out but when i test this feature,by clicking and holding a cell, then sometime it pop up creation form and sometime it do not pop up form.

**Comment by kurorido** [comment]
Hi, @antoniandre thank you for a such great feature.
I think maybe you can provide a callback to tell "which cell is clicked or pressed".  It will let others customize the behavior easily.

I suggest to emit "cell-mouse-down" event in https://github.com/antoniandre/vue-cal/blob/48eac0a5476f605f33dc55a8939ab4210c2a30da/src/components/vue-cal/index.vue#L405

If you think it's fine, I will send a pull request :)

**Comment by kurorido** [comment]
Hi, @anhnguyenpku , according to the source code. 
You'll need to hold the cell about 1.2s to trigger the event.

https://github.com/antoniandre/vue-cal/blob/48eac0a5476f605f33dc55a8939ab4210c2a30da/src/components/vue-cal/index.vue#L224

**Comment by antoniandre** [comment]
Hi @kurorido, @anhnguyenpku,

Thank you for your feedbacks.

> You'll need to hold the cell about 1.2s to trigger the event.

@anhnguyenpku: @kurorido is correct, but do you mean it does not work in your code or when you try the examples of the documentation?
- https://antoniandre.github.io/vue-cal/#ex--edit-delete-create-events
- https://antoniandre.github.io/vue-cal/#ex--more-advanced-event-creation

@kurorido, thanks for your suggestion of PR. Actually there are already a `day-click` & `day-focus` events (will be renamed to `cell-click` & `cell-focus` in next version) 
ref. https://antoniandre.github.io/vue-cal/#ex--emitted-events.
But in the context of event creation, what I can do is add 2 parameters to the callback function triggered on `:on-event-create`.
- the original DOM event object from clicking & holding the cell (where you can get mouse coordinates)
- the clicked cell object with date info and more

This will be available in the next release.

**Comment by anhnguyenpku** [comment]
Hi, @antoniandre
You'll need to hold the cell about 1.2s to trigger the event.
yes, it work ok.
I'm waiting for next release with new feature.
Thanks.

**Comment by antoniandre** [comment]
Hi @anhnguyenpku, @kurorido, @ArjenSwBase,

A new version is released and emitted events `day-click` & `day-focus` are now renamed into `cell-click` & `cell-focus`, along with fixes and improvements.

Regarding the parameters you get on cell click and hold, I haven't changed it in the release since you already have all you need in the event: the exact start date and time, and the event itself that you can modify on the fly as demonstrated in https://antoniandre.github.io/vue-cal/#ex--more-advanced-event-creation.

There is also a related feature request you might be interested in: #94.
If so please vote in that thread.

I will close this issue now as the feature is out.
Please reopen if there is a bug.

Thanks all for your support and feedbacks!
