### ISSUE TITLE
Possible bug when clicking on a multiple day event

### ISSUE THREAD

**Issue by aocneanu** [antoniandre/vue-cal-v4#70]
Hello,

Congrats for what you've done with this lib!

I'm looking forward to have vue-cal fully integrated with my OSS project.

While playing with multiple day events I'm getting an inconsistency when using `on-event-dblclick`.

![image](https://user-images.githubusercontent.com/16073274/54867275-251b9880-4d87-11e9-878d-57ff7fabd75f.png)

Notice the id of the logged event

![image](https://user-images.githubusercontent.com/16073274/54867288-4f6d5600-4d87-11e9-8efd-dda6da453d83.png)

Any clue ?

Thank you!

**Comment by antoniandre** [comment]
Hi @aocneanu, thank you for your feedbacks!
Well this is because the `id` attribute is a reserved attribute for the internal identification of events.
So the id that you first set is overridden by internal process.
For now you can fix this by using another key instead of `id`.

But as you point it out, it makes sense to keep this key available for the end-user of the lib and internally use another key name that would not conflict like `vuecalEventId`.
I will do so in a next release! 👌

**Comment by aocneanu** [comment]
Ah cool, thanks.

Could you provide some insights about how you’re planning to handle recurring events, if it’s not too soon? I saw that it’s on the roadmap.

**Comment by antoniandre** [comment]
Hi @aocneanu, from version 1.43.1 the event `id` key is now available for use by everyone.
Hope it solves your issue.

Regarding the recurring events, it will behave very similarly to multiple-day events:  https://antoniandre.github.io/vue-cal/#ex--multiple-day-events
So you will have this event listed only once in your array of events with the attribute `recurring`,
and it will probably accept an array of days.

But internally vue-cal will duplicate this event to render where needed, exactly like multiple-day events.

**Comment by aocneanu** [comment]
>from version 1.43.1 the event id key is now available for use by everyone.
Hope it solves your issue.

That's great, thank you.

About recurring events I will wait until "the time comes" :)

**Comment by antoniandre** [comment]
I will update the documentation to warn that the `eid` key is taken. :)
