### ISSUE TITLE
Overlapping not working

### ISSUE THREAD

**Issue by vitorhugosg** [antoniandre/vue-cal-v4#89]
Hello, good. First of all, I thank you for this super tool.

To with a doubt, in the documentation, I saw that it has an overlapping, however when I put more than one event at the same time, one event is over the other, it follows code:
<vue-cal
          
          v-if="!loader"
          :locale="'pt-br'"
          :events="calendario"
          :show-all-day-events="true"
          :disable-views="['years']"
          :on-event-click="onEventClick"
          :no-event-overlaps="false"
        >

And also follows the image:

![FireShot Capture 032 - CredDente, Gerenciamento Cliníco - localhost](https://user-images.githubusercontent.com/17458174/55991758-6239c300-5c81-11e9-82ac-4f3a6a0ef209.png)
Do you know if I'm doing something wrong?

**Comment by antoniandre** [comment]
Hi @vitorhugosg, thanks for your feedbacks.

Are you trying to prevent overlaps? Currently Vue Cal, does not prevent simultaneous events, but is has the ability to display side by side in same cell or in overlapping manner.
Follow this example and try toggling the button to see the difference: https://antoniandre.github.io/vue-cal/#ex--overlapping-events

Otherwise, your code looks good for that part, if you still need help please give me the full code and screenshot or a codepen example.

Cheers.

**Comment by vitorhugosg** [comment]
Hello, thank you very much for the answer.
So I tried with true, or false in the "no-event-overlaps" directive, but without success, in my case I want to show an event next to the other, know how I dont can proceed, only css that I put was the colors of the events.

**Comment by antoniandre** [comment]
Hi @vitorhugosg,
Here is another example for you to try: https://codepen.io/antoniandre/pen/eoEgqo.
You can change the value in the html line 7: `:no-event-overlaps="true"` to true/false to understand what it changes, this is only changing the way 2 simultaneous events are displayed, overlapping or not.

I suggest you do your tests in this started codepen, and if you still have question you can give me the updated codepen link again and we will work from there.
I am sorry I don't really understand what is the issue.

**Comment by antoniandre** [comment]
Closed for inactivity. Please reopen if not solved.
